language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
  #- '8'
  #- '6'
jobs:
  include:
    - stage: deploy
      script: ./deploy.sh
script:
  - ./test.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
