export { Func } from './types/Func'
export { UnaryFunction } from './types/UnaryFunction'
export { deferP0 } from './deferP0'
export { applyArgs } from './applyArgs'
export { compose } from './compose'
export { pipe } from './pipe'