type UF<TIn, TOut> = (x: TIn) => TOut

function pipeImpl<T, R>(...operations: UF<any, any>[]): UF<T, R> {
  return (v: T) => operations.reduce((acc, f) => f(acc), v as any)
}

function _pipe<T, A>(f1: UF<T, A>): UF<T, A>
function _pipe<T, A, B>(f1: UF<T, A>, f2: UF<A, B>): UF<T, B>
function _pipe<T, A, B, C>(f1: UF<T, A>, f2: UF<A, B>, f3: UF<B, C>): UF<T, C>
function _pipe<T, A, B, C, D>(f1: UF<T, A>, f2: UF<A, B>, f3: UF<B, C>, f4: UF<C, D>): UF<T, D>
function _pipe<T, A, B, C, D, E>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>
): UF<T, E>
function _pipe<T, A, B, C, D, E, F>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>
): UF<T, F>
function _pipe<T, A, B, C, D, E, F, G>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>
): UF<T, G>
function _pipe<T, A, B, C, D, E, F, G, H>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>
): UF<T, H>
function _pipe<T, A, B, C, D, E, F, G, H, I>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>
): UF<T, I>
function _pipe<T, A, B, C, D, E, F, G, H, I, J>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>
): UF<T, J>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>
): UF<T, K>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>
): UF<T, L>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L, M>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>
): UF<T, M>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>
): UF<T, N>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>
): UF<T, O>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>
): UF<T, P>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>
): UF<T, Q>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>
): UF<T, R>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>,
  f19: UF<R, S>
): UF<T, S>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>,
  f19: UF<R, S>,
  f20: UF<S, U>
): UF<T, U>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>,
  f19: UF<R, S>,
  f20: UF<S, U>,
  f21: UF<U, V>
): UF<T, V>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>,
  f19: UF<R, S>,
  f20: UF<S, U>,
  f21: UF<U, V>,
  f22: UF<V, W>
): UF<T, W>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W, X>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>,
  f19: UF<R, S>,
  f20: UF<S, U>,
  f21: UF<U, V>,
  f22: UF<V, W>,
  f23: UF<W, X>
): UF<T, X>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W, X, Y>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>,
  f19: UF<R, S>,
  f20: UF<S, U>,
  f21: UF<U, V>,
  f22: UF<V, W>,
  f23: UF<W, X>,
  f24: UF<X, Y>
): UF<T, Y>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W, X, Y, Z>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>,
  f19: UF<R, S>,
  f20: UF<S, U>,
  f21: UF<U, V>,
  f22: UF<V, W>,
  f23: UF<W, X>,
  f24: UF<X, Y>,
  f25: UF<Y, Z>
): UF<T, Z>
function _pipe<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W, X, Y, Z, AA>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>,
  f19: UF<R, S>,
  f20: UF<S, U>,
  f21: UF<U, V>,
  f22: UF<V, W>,
  f23: UF<W, X>,
  f24: UF<X, Y>,
  f25: UF<Y, Z>,
  f26: UF<Z, AA>
): UF<T, AA>
function _pipe<
  T,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB
>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>,
  f19: UF<R, S>,
  f20: UF<S, U>,
  f21: UF<U, V>,
  f22: UF<V, W>,
  f23: UF<W, X>,
  f24: UF<X, Y>,
  f25: UF<Y, Z>,
  f26: UF<Z, AA>,
  f27: UF<AA, AB>
): UF<T, AB>
function _pipe<
  T,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC
>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>,
  f19: UF<R, S>,
  f20: UF<S, U>,
  f21: UF<U, V>,
  f22: UF<V, W>,
  f23: UF<W, X>,
  f24: UF<X, Y>,
  f25: UF<Y, Z>,
  f26: UF<Z, AA>,
  f27: UF<AA, AB>,
  f28: UF<AB, AC>
): UF<T, AC>
function _pipe<
  T,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD
>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>,
  f19: UF<R, S>,
  f20: UF<S, U>,
  f21: UF<U, V>,
  f22: UF<V, W>,
  f23: UF<W, X>,
  f24: UF<X, Y>,
  f25: UF<Y, Z>,
  f26: UF<Z, AA>,
  f27: UF<AA, AB>,
  f28: UF<AB, AC>,
  f29: UF<AC, AD>
): UF<T, AD>
function _pipe<
  T,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE
>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>,
  f19: UF<R, S>,
  f20: UF<S, U>,
  f21: UF<U, V>,
  f22: UF<V, W>,
  f23: UF<W, X>,
  f24: UF<X, Y>,
  f25: UF<Y, Z>,
  f26: UF<Z, AA>,
  f27: UF<AA, AB>,
  f28: UF<AB, AC>,
  f29: UF<AC, AD>,
  f30: UF<AD, AE>
): UF<T, AE>
function _pipe<
  T,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF
>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>,
  f19: UF<R, S>,
  f20: UF<S, U>,
  f21: UF<U, V>,
  f22: UF<V, W>,
  f23: UF<W, X>,
  f24: UF<X, Y>,
  f25: UF<Y, Z>,
  f26: UF<Z, AA>,
  f27: UF<AA, AB>,
  f28: UF<AB, AC>,
  f29: UF<AC, AD>,
  f30: UF<AD, AE>,
  f31: UF<AE, AF>
): UF<T, AF>
function _pipe<
  T,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG
>(
  f1: UF<T, A>,
  f2: UF<A, B>,
  f3: UF<B, C>,
  f4: UF<C, D>,
  f5: UF<D, E>,
  f6: UF<E, F>,
  f7: UF<F, G>,
  f8: UF<G, H>,
  f9: UF<H, I>,
  f10: UF<I, J>,
  f11: UF<J, K>,
  f12: UF<K, L>,
  f13: UF<L, M>,
  f14: UF<M, N>,
  f15: UF<N, O>,
  f16: UF<O, P>,
  f17: UF<P, Q>,
  f18: UF<Q, R>,
  f19: UF<R, S>,
  f20: UF<S, U>,
  f21: UF<U, V>,
  f22: UF<V, W>,
  f23: UF<W, X>,
  f24: UF<X, Y>,
  f25: UF<Y, Z>,
  f26: UF<Z, AA>,
  f27: UF<AA, AB>,
  f28: UF<AB, AC>,
  f29: UF<AC, AD>,
  f30: UF<AD, AE>,
  f31: UF<AE, AF>,
  f32: UF<AF, AG>
): UF<T, AG>
function _pipe<T, R>(...operations: UF<any, any>[]): UF<T, R> {
  return pipeImpl(...operations)
}

export const pipe = _pipe

export function typedPipe<T>() {
  function p<A>(f1: UF<T, A>): UF<T, A>
  function p<A, B>(f1: UF<T, A>, f2: UF<A, B>): UF<T, B>
  function p<A, B, C>(f1: UF<T, A>, f2: UF<A, B>, f3: UF<B, C>): UF<T, C>
  function p<A, B, C, D>(f1: UF<T, A>, f2: UF<A, B>, f3: UF<B, C>, f4: UF<C, D>): UF<T, D>
  function p<A, B, C, D, E>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>
  ): UF<T, E>
  function p<A, B, C, D, E, F>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>
  ): UF<T, F>
  function p<A, B, C, D, E, F, G>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>
  ): UF<T, G>
  function p<A, B, C, D, E, F, G, H>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>
  ): UF<T, H>
  function p<A, B, C, D, E, F, G, H, I>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>
  ): UF<T, I>
  function p<A, B, C, D, E, F, G, H, I, J>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>
  ): UF<T, J>
  function p<A, B, C, D, E, F, G, H, I, J, K>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>
  ): UF<T, K>
  function p<A, B, C, D, E, F, G, H, I, J, K, L>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>
  ): UF<T, L>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>
  ): UF<T, M>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>
  ): UF<T, N>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>
  ): UF<T, O>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>
  ): UF<T, P>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>
  ): UF<T, Q>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>
  ): UF<T, R>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>
  ): UF<T, S>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>
  ): UF<T, U>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>
  ): UF<T, V>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>
  ): UF<T, W>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W, X>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>
  ): UF<T, X>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W, X, Y>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>
  ): UF<T, Y>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W, X, Y, Z>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>
  ): UF<T, Z>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W, X, Y, Z, AA>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>,
    f26: UF<Z, AA>
  ): UF<T, AA>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W, X, Y, Z, AA, AB>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>,
    f26: UF<Z, AA>,
    f27: UF<AA, AB>
  ): UF<T, AB>
  function p<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W, X, Y, Z, AA, AB, AC>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>,
    f26: UF<Z, AA>,
    f27: UF<AA, AB>,
    f28: UF<AB, AC>
  ): UF<T, AC>
  function p<
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    U,
    V,
    W,
    X,
    Y,
    Z,
    AA,
    AB,
    AC,
    AD
  >(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>,
    f26: UF<Z, AA>,
    f27: UF<AA, AB>,
    f28: UF<AB, AC>,
    f29: UF<AC, AD>
  ): UF<T, AD>
  function p<
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    U,
    V,
    W,
    X,
    Y,
    Z,
    AA,
    AB,
    AC,
    AD,
    AE
  >(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>,
    f26: UF<Z, AA>,
    f27: UF<AA, AB>,
    f28: UF<AB, AC>,
    f29: UF<AC, AD>,
    f30: UF<AD, AE>
  ): UF<T, AE>
  function p<
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    U,
    V,
    W,
    X,
    Y,
    Z,
    AA,
    AB,
    AC,
    AD,
    AE,
    AF
  >(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>,
    f26: UF<Z, AA>,
    f27: UF<AA, AB>,
    f28: UF<AB, AC>,
    f29: UF<AC, AD>,
    f30: UF<AD, AE>,
    f31: UF<AE, AF>
  ): UF<T, AF>
  function p<
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    U,
    V,
    W,
    X,
    Y,
    Z,
    AA,
    AB,
    AC,
    AD,
    AE,
    AF,
    AG
  >(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>,
    f26: UF<Z, AA>,
    f27: UF<AA, AB>,
    f28: UF<AB, AC>,
    f29: UF<AC, AD>,
    f30: UF<AD, AE>,
    f31: UF<AE, AF>,
    f32: UF<AF, AG>
  ): UF<T, AG>
  function p<R>(...operations: UF<any, any>[]): UF<T, R> {
    return pipeImpl(...operations)
  }
  return p
}

export function pipeValue<T>(src: T) {
  function invokePipe<A>(f1: UF<T, A>): A
  function invokePipe<A, B>(f1: UF<T, A>, f2: UF<A, B>): B
  function invokePipe<A, B, C>(f1: UF<T, A>, f2: UF<A, B>, f3: UF<B, C>): C
  function invokePipe<A, B, C, D>(f1: UF<T, A>, f2: UF<A, B>, f3: UF<B, C>, f4: UF<C, D>): D
  function invokePipe<A, B, C, D, E>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>
  ): E
  function invokePipe<A, B, C, D, E, F>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>
  ): F
  function invokePipe<A, B, C, D, E, F, G>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>
  ): G
  function invokePipe<A, B, C, D, E, F, G, H>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>
  ): H
  function invokePipe<A, B, C, D, E, F, G, H, I>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>
  ): I
  function invokePipe<A, B, C, D, E, F, G, H, I, J>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>
  ): J
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>
  ): K
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K, L>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>
  ): L
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K, L, M>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>
  ): M
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>
  ): N
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>
  ): O
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>
  ): P
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>
  ): Q
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>
  ): R
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>
  ): S
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>
  ): U
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>
  ): V
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>
  ): W
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W, X>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>
  ): X
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W, X, Y>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>
  ): Y
  function invokePipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, U, V, W, X, Y, Z>(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>
  ): Z
  function invokePipe<
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    U,
    V,
    W,
    X,
    Y,
    Z,
    AA
  >(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>,
    f26: UF<Z, AA>
  ): AA
  function invokePipe<
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    U,
    V,
    W,
    X,
    Y,
    Z,
    AA,
    AB
  >(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>,
    f26: UF<Z, AA>,
    f27: UF<AA, AB>
  ): AB
  function invokePipe<
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    U,
    V,
    W,
    X,
    Y,
    Z,
    AA,
    AB,
    AC
  >(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>,
    f26: UF<Z, AA>,
    f27: UF<AA, AB>,
    f28: UF<AB, AC>
  ): AC
  function invokePipe<
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    U,
    V,
    W,
    X,
    Y,
    Z,
    AA,
    AB,
    AC,
    AD
  >(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>,
    f26: UF<Z, AA>,
    f27: UF<AA, AB>,
    f28: UF<AB, AC>,
    f29: UF<AC, AD>
  ): AD
  function invokePipe<
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    U,
    V,
    W,
    X,
    Y,
    Z,
    AA,
    AB,
    AC,
    AD,
    AE
  >(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>,
    f26: UF<Z, AA>,
    f27: UF<AA, AB>,
    f28: UF<AB, AC>,
    f29: UF<AC, AD>,
    f30: UF<AD, AE>
  ): AE
  function invokePipe<
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    U,
    V,
    W,
    X,
    Y,
    Z,
    AA,
    AB,
    AC,
    AD,
    AE,
    AF
  >(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>,
    f26: UF<Z, AA>,
    f27: UF<AA, AB>,
    f28: UF<AB, AC>,
    f29: UF<AC, AD>,
    f30: UF<AD, AE>,
    f31: UF<AE, AF>
  ): AF
  function invokePipe<
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    U,
    V,
    W,
    X,
    Y,
    Z,
    AA,
    AB,
    AC,
    AD,
    AE,
    AF,
    AG
  >(
    f1: UF<T, A>,
    f2: UF<A, B>,
    f3: UF<B, C>,
    f4: UF<C, D>,
    f5: UF<D, E>,
    f6: UF<E, F>,
    f7: UF<F, G>,
    f8: UF<G, H>,
    f9: UF<H, I>,
    f10: UF<I, J>,
    f11: UF<J, K>,
    f12: UF<K, L>,
    f13: UF<L, M>,
    f14: UF<M, N>,
    f15: UF<N, O>,
    f16: UF<O, P>,
    f17: UF<P, Q>,
    f18: UF<Q, R>,
    f19: UF<R, S>,
    f20: UF<S, U>,
    f21: UF<U, V>,
    f22: UF<V, W>,
    f23: UF<W, X>,
    f24: UF<X, Y>,
    f25: UF<Y, Z>,
    f26: UF<Z, AA>,
    f27: UF<AA, AB>,
    f28: UF<AB, AC>,
    f29: UF<AC, AD>,
    f30: UF<AD, AE>,
    f31: UF<AE, AF>,
    f32: UF<AF, AG>
  ): AG
  function invokePipe<R>(...operations: UF<any, any>[]): R {
    const p = pipeImpl<T, R>(...operations)
    return p(src)
  }
  return { into: invokePipe }
}
