name: Release

on:
    push:
        branches: [master, beta]

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: npx ci
            - name: Install semantic-release extra plugins
              run: npm install --save-dev @semantic-release/changelog @semantic-release/git
            - name: Lint
              run: npm run lint
            - name: Test
              run: npm run test -- --no-cache
            - name: Build
              run: npm run build
            - name: Build docs
              run: npm run build-docs
            - name: Deploy docs
              if: github.ref == 'refs/heads/master'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npm run deploy-docs
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm run semantic-release
